spring:
  applications:
    name: customer
  datasource:
    username: 'user'
    url: jdbc:postgresql://172.20.0.3:5432/customer
    password: 'admin'
  jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
      show-sql: 'true'
